development:
  adapter: async
  url: ws://localhost:3001/wrtc

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: apk_production
